// Config:
export const GET_CONFIG = 'GET_CONFIG';
export const GET_CONFIG_PENDING = 'GET_CONFIG_PENDING';
export const GET_CONFIG_FULFILLED = 'GET_CONFIG_FULFILLED';
export const GET_CONFIG_REJECTED = 'GET_CONFIG_REJECTED';

// Single:
export const GET_SINGLE = 'GET_SINGLE';
export const GET_SINGLE_PENDING = 'GET_SINGLE_PENDING';
export const GET_SINGLE_FULFILLED = 'GET_SINGLE_FULFILLED';
export const GET_SINGLE_REJECTED = 'GET_SINGLE_REJECTED';

// Search:
export const SEARCH = 'SEARCH';
export const SEARCH_PENDING = 'SEARCH_PENDING';
export const SEARCH_FULFILLED = 'SEARCH_FULFILLED';
export const SEARCH_REJECTED = 'SEARCH_REJECTED';

// Reset:
export const API_RESET = 'API_RESET';

// Forms:
export const SEND_FORM = 'SEND_FORM';
export const RESET_FORM = 'RESET_FORM';
export const SEND_FORM_PENDING = 'SEND_FORM_PENDING';
export const SEND_FORM_FULFILLED = 'SEND_FORM_FULFILLED';
export const SEND_FORM_REJECTED = 'SEND_FORM_REJECTED';

// Load by Category:
export const LOAD_SECTION = 'LOAD_SECTION';
export const LOAD_SECTION_PENDING = 'LOAD_SECTION_PENDING';
export const LOAD_SECTION_FULFILLED = 'LOAD_SECTION_FULFILLED';
export const LOAD_SECTION_REJECTED = 'LOAD_SECTION_REJECTED';
